version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    restart: "no"
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    networks:
      - default

  db:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    networks:
      - default